### ISSUE TITLE
The P4 vscode Extension server crashed

### ISSUE THREAD

**Issue by Sunxiangpeng0531** [fattaholmanan/p4-vscode-extension#7]
Hi, I installed your extension on my machine. However, the vscode keep showing that "The P4 vscode Extension server crashed" and the output is **"Error: Cannot find module '/home/xiangpeng/.vscode-server/extensions/fattaholmanan.p4-vscode-extension-0.1.2/node_modules/ts-pq/lib/priorityQueue.js'. Please verify that the package.json has a valid "main" entry"**. I think this may due to some dependency of the priorityQueue.js but I'm not familiar with js/ts, can you please check that? Thank you very much for the extention!

**Comment by jeremias-work** [comment]
I observed the same issue:

```
[Info  - 5:18:45 PM] Connection to server got closed. Server will restart.
internal/modules/cjs/loader.js:236
      throw err;
      ^

Error: Cannot find module '/home/jblendin/.vscode-server/extensions/fattaholmanan.p4-vscode-extension-0.1.2/node_modules/ts-pq/lib/priorityQueue.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:228:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:365:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:27)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/home/jblendin/.vscode-server/extensions/fattaholmanan.p4-vscode-extension-0.1.2/server/out/utils/interval_ds.js:4:17)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/home/jblendin/.vscode-server/extensions/fattaholmanan.p4-vscode-extension-0.1.2/node_modules/ts-pq/package.json',
  requestPath: 'ts-pq'
}
[Error - 5:18:45 PM] Connection to server got closed. Server will not be restarted.
```

**Comment by fattaholmanan** [comment]
I moved the PriorityQueue class to the source code. It should be fixed now. Give it a try.
